### ISSUE TITLE
Create release

### ISSUE THREAD

**Issue by lbartoletti** [lumina-desktop/lumina-pdf#4]
Please, can you versioning and create release for this tool?
I used [tagname](https://svnweb.freebsd.org/ports/head/deskutils/lumina-pdf/Makefile?revision=513196&view=markup#l20) for the FreeBSD port when I updated Lumina to 1.5.0. But the tools isn't clearly tagged as 1.5.0.

Thank you

**Comment by beanpole135** [comment]
Done! There is a new "v1.5.0" tag for packaging utilities to use.
